version: '3.8'

services:
  db:
    image: postgres:15
    container_name: kn-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  server:
    build:
      context: ./server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    container_name: kn-server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db
    environment:
      DB_URL: postgres://${DB_USER}:${DB_PASS}@db:${DB_PORT}/${DB_NAME}
      SERVER_PORT: ${SERVER_PORT}
      SERVER_URL: ${SERVER_URL}
      NODE_ENV: development

  client:
    build: 
      context: ./client
    volumes:
      - ./client:/usr/src/app  
      - /usr/src/app/node_modules 
    container_name: kn-client
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
      CLIENT_URL: ${CLIENT_URL}
      NODE_ENV: development
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    depends_on:
      - server
