version: '3.8'

services:
  db:
    image: postgres:15
    container_name: kn_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_PORT: ${DB_PORT}

    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"

  server:
    build: 
      context: ./server
    container_name: kn_server
    depends_on:
      - db
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db
    environment:
      DB_URL: postgres://${DB_USER}:${DB_PASS}@db:${DB_PORT}/${DB_NAME}
      SERVER_PORT: ${SERVER_PORT}
      SERVER_URL: ${SERVER_URL}


  client:
    build: ./client
    container_name: kn_client
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
    ports:
      - "${CLIENT_PORT}:80"
    depends_on:
      - server

volumes:
  db-data:
